import os
import glob

GRAPH_PATHS = glob.glob("out/*_cluster/out_*")
GRAPH_ENTRIES = [
    (os.path.basename(os.path.dirname(p)), os.path.basename(p))
    for p in GRAPH_PATHS
    if os.path.isdir(p)
]

def all_targets(wildcards):
    return [
        f"out/{cluster}/{out_dir}/gen_ftr1/done.txt"
        for cluster, out_dir in GRAPH_ENTRIES
    ]

rule all:
    input: all_targets

rule generate_ftr1:
    input:
        gml=lambda wildcards: f"out/{wildcards.cluster}/{wildcards.out_dir}/{wildcards.out_dir.replace('out_', '', 1)}.gml"
    wildcard_constraints:
        cluster="[^/]+_cluster",
        out_dir="out_[^/]+"
    output:
        done="out/{cluster}/{out_dir}/gen_ftr1/done.txt"
    log:
        "out/{cluster}/{out_dir}/gen_ftr1/run.log"
    shell:
        "timeout 3600 python -m kedgeswap.main -f {input.gml} "
        "-o out/{wildcards.cluster}/{wildcards.out_dir}/gen_ftr1/g "
        "-gml -v -a -g 3 --output_number 50 -ftr 1 -acfs 2>&1 | tee {log} && "
        "echo done > {output.done}"